.prettierrc.json
README.md
client/.gitignore

Initial Readme. This is probably always a WIP as things change, but this is a good starting point.

USNP23 ReadMe

---

.github/PULL_REQUEST_TEMPLATE.md

The changes in this PR include a new folder, .github, and a new file, GITHUB_PULL_REQUEST_TEMPLATE.md, that will be used for each Pull Request going forward. 
---
Github automatically recognizes the .github/ directory as a configuration directory, and will implement the PR template in future pull requests made in this repo. According to ChatGPT. 
---
Original Issue: https://github.com/RubySpeeders/US-Navy-Project/issues/36
---
---

USNP36 Establish Pull Request Template 

---

README.md

- The PR updates the readme to take into account the official new name of the project, Drum Roulette!
---
- Updates all mentions of USNP and changes it to DR
---
Original Issue: https://github.com/RubySpeeders/Drum-Roulette/issues/64
---
---
---

DR 64 updating readme

---

client/src/pages/assignments.tsx

- The changes in this PR to test if pushing from develop --> main triggers a deployment
---
---
---
---
---

deployment-test

---

.github/ISSUE_TEMPLATE/generic-issue-template.md
.vscode/launch.json
client/src/pages/selection.tsx

- This PR addresses the bug where users can click the "give me assignments" button when there are no musicians or instruments selected.
---
- Creates a new `useEffect()` hook that sets state variable `isSelected` to true if there are at least two musicians & instruments selected.
- If `isSelected` is true, the button is enabled.
---
Original Issue: [DR-84](https://github.com/RubySpeeders/Drum-Roulette/issues/84)
---
---
---

DR-84-disable-button

---

client/src/pages/_app.tsx
client/src/pages/landing.tsx
client/src/styles/theme.ts

- The changes in this PR add default values to the material ui theme, perform a basic CSS reset, and add styling to the landing page.
---
- Replaces copy on existing landing page to match Figma prototype
- Performs css reset using CssBaseLine component from Material ui (normalizes padding, margins, box-sizing, etc.) 
- Adds inter as a font to material ui theme
- Adds default background and primary text colors to material ui theme 
- Alters material ui theme to remove text decoration from all anchor tags by default
- Adds module augmentation for material ui DefaultTheme (Typescript fix necessary in MUI v5)
- Adds styling to landing page to match Figma prototype
---
Original Issue: https://github.com/users/RubySpeeders/projects/1/views/1?pane=issue&itemId=37304424
Depends …

finished landing page styling

---

client/src/pages/_app.tsx
client/src/pages/assignments.tsx
client/src/styles/theme.ts
client/tsconfig.json

"Back to Selection Page" button will take the user back to the selection page. 
*Next step - find a way to style the button consistently across all pages
Original Issue: https://github.com/users/RubySpeeders/projects/1?pane=issue&itemId=38078409
---
---
---

DR-93-back-to-selection-page

---

client/src/components/CustomButton.tsx
client/src/pages/selection.tsx
client/src/styles/theme.ts

---
This PR builds a reusable custom button component.
---
Original Issue: [DR-118](https://github.com/RubySpeeders/Drum-Roulette/issues/118)
---
---
---

DR 118 reusable button component

---

client/src/app/ThemeRegistry.tsx
client/src/app/assignments/page.tsx
client/src/app/selection/page.tsx
client/src/components/itemCard.tsx
client/src/components/landing.tsx
client/src/components/selectItemCard.tsx
client/src/components/selectionContainer.tsx
client/src/components/selector.tsx
client/src/interfaces/instrument.ts
client/src/utils/api/getMusicians.ts
client/src/utils/assign.ts

SP DR-114 update next

---

.github/workflows/lambda.yaml

---
The changes in this PR replace the installation of AWS CLI in the gh action.
---
---
---
---

updating AWS CLI command

---

.github/workflows/lambda.yaml

removing the yumminess from aws

---

.github/workflows/lambda.yaml

remove that pseudo sudo

---

.github/workflows/lambda.yaml

possible more debug info

---

backend/lambda/musicians/navy/get/index.mjs
client/src/app/assignments/page.tsx
client/src/components/selectionContainer.tsx
client/src/interfaces/musician.ts

…ckend
---
- The changes in this PR updates the data returned from the backend to use `musician` instead of `user`
- replaced `user` with `musician` for `Musician` type and where musicians are displayed on the selection page
---
---
---
---

DR-148-FE-hotfix-user-to-musician

---

client/src/components/selectionContainer.tsx

This PR adds a link to the selection page that returns the user to the landing page (homepage).
---
- Adds `<Link />` on selection page to return to the landing page.
---
---
---
---

DR-95-adding-link-return-to-homepage

---

README.md

Added a screenshot of the landing page 
---
The image URL taken from Github
---

DR 44B Update README

---

client/src/app/assignments/page.tsx
client/src/components/ItemCard.tsx
client/src/components/SelectionContainer.tsx

---
---
Original Issue: [DR-48](https://www.notion.so/Refactor-Assignments-Page-code-06c91f3694e24f079297a7af41ae303c)
---
---
---

DR 48 assignments page code refactor

---

client/package.json

added MIT license

---

client/src/components/ItemCard.tsx
client/src/components/SelectionContainer.tsx

DR-31 button jump

---

.gitignore
client/src/app/assignments/page.tsx
client/src/app/layout.tsx
client/src/components/AssignmentBox.tsx
client/src/components/CustomButton.tsx
client/src/components/Header.tsx
client/src/components/ItemCard.tsx
client/src/styles/theme.ts
next-env.d.ts

- This PR matches the assignments page styling to the Figma design
---
- Added new component AssignmentBox.tsx
- Added custom breakpoint to MUI theme to accommodate responsive design
- Cleaned up styling in ItemCard.tsx and assignments page (assignments/page.tsx)
---
Original Issue: https://www.notion.so/Assignments-Page-to-match-Figma-Designs-f0f3a1062d5a46fdb8065976541f417b
---
---
---

Dr 27 assignments page

---

client/src/components/CustomButton.tsx

button style fix

---

client/src/app/api/branches/route.ts
client/src/app/api/musicians/[branch_name]/route.ts
client/src/app/api/musicians/route.ts
client/src/types/custom.d.ts
client/src/utils/kebabToTitle.ts

---
testing and adding backend logic only.
---
---
---
---

backend cupdates

---

src/components/BranchLogo.tsx
src/components/ItemGrid.tsx
src/components/SelectionContainer.tsx

---
This PR introduces styling in mobile views that makes the musicians and instruments horizontally scrollable for an easier view.
---
---
---
---

Scrollable Musicians & Items in mobile view

---

src/components/ItemCard.tsx
src/components/ItemGrid.tsx
src/components/SelectionContainer.tsx

---
This PR fixes where the selected class is applied; the border is now applied to the outside of only the image in the `ItemCard`
---
---
---
---

Selected Class Improvement

---

src/components/BranchLogo.tsx
src/components/Header.tsx
src/components/Landing.tsx
src/components/SelectionContainer.tsx

---
This PR adds style changes to update the UI of the landing page.
---
---
---
---

Landing Page Updates

---

next.config.js
src/app/assignments/page.tsx
src/components/AssignmentBox.tsx
src/components/CustomButton.tsx
src/components/Header.tsx
src/components/ItemCard.tsx
src/components/ItemGrid.tsx
src/components/SelectionContainer.tsx
src/interfaces/instrument.ts

Styling Overhaul for Mobile on Assignment Page

---

README.md
documentation/frontEndDocs.md

update readme and add fe docs
